package Bett::Model::MoodleDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

# use Catalyst;
# use Bett;

# my $name = Bett->config->{dic_database};
my $name = "mood";

__PACKAGE__->config(
    schema_class => 'Bett::MoodleSchema',
    connect_info => {
        dsn => "dbi:Pg:dbname=$name;port=5433",
        user => 'apache',
        password => '',
    }
);

=head1 NAME

Bett::Model::MoodleDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Bett>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Bett::MoodleSchema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.29

=head1 AUTHOR

Dr Bean

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
